require 'net/http'
require 'json'
require 'date'

def fetch(url, token)
  uri = URI(url)
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  request = Net::HTTP::Get.new(uri.request_uri, {
    'Authorization' => "token #{token}",
    'User-Agent' => 'Ruby'
  })
  response = http.request(request)
  JSON.parse(response.body)
end

def count_user_commits(username, token)
  base_url = "https://api.github.com"
  end_date = DateTime.now
  start_date = end_date - 30

  puts "🚀 Launching github commit counter..."

  # Fetch all repositories for the authenticated user
  page = 1
  all_repos = []
  loop do
    repos_url = "#{base_url}/user/repos?page=#{page}&per_page=100"
    repos = fetch(repos_url, token)
    break if repos.empty?

    all_repos.concat(repos)
    page += 1
  end

  commit_count = 0
  lines_added = 0
  lines_removed = 0

  # Iterate over repositories
  all_repos.each do |repo|
    puts "🔍 Checking repo: #{repo['name']}..."
    branches_url = "#{repo['url']}/branches"
    branches = fetch(branches_url, token)

    branches.each do |branch|
      puts "   - Checking branch: #{branch['name']}..."
      commits_url = "#{repo['url']}/commits?since=#{start_date.iso8601}&sha=#{branch['name']}"

      # Fetch commits
      commits = fetch(commits_url, token)

      # Count commits, lines added, and lines removed within the last 30 days
      commits.each do |commit|
        commit_date = DateTime.parse(commit['commit']['committer']['date'])
        if commit_date.between?(start_date, end_date)
          commit_count += 1
          puts "      ↳ Found a commit! Running total: #{commit_count} commits"

          commit_detail = fetch(commit['url'], token)
          lines_added += commit_detail['stats']['additions']
          lines_removed += commit_detail['stats']['deletions']
        end
      end
    end
  end

  puts "🎉 Finished counting commits!"

  {
    username: username,
    commits: commit_count,
    lines_added: lines_added,
    lines_removed: lines_removed,
    start_date: start_date.strftime("%B %d, %Y"),
    end_date: end_date.strftime("%B %d, %Y")
  }
end

# Replace 'your_github_token' with your actual GitHub token
# Replace 'username' with the GitHub username you want to check
stats = count_user_commits('username', 'token')

border_line = "+" + "-" * 62 + "+"
empty_line = "|" + " " * 62 + "|"

puts ""
puts ""
puts border_line
puts empty_line
line = "| 🚀 GitHub Contribution Stats for #{stats[:username]} 🚀"
puts line + " " * (border_line.length - line.length - 3) + "|"

line = "| 📅 From #{stats[:start_date]} to #{stats[:end_date]} 📅"
puts line + " " * (border_line.length - line.length - 3) + "|"
puts empty_line

line = "| 🔥 Total Commits: #{stats[:commits].to_s}"
puts line + " " * (border_line.length - line.length - 2) + "|"

line = "| ➕ Total Lines Added: #{stats[:lines_added].to_s}"
puts line + " " * (border_line.length - line.length - 1) + "|"

line = "| ➖ Total Lines Removed: #{stats[:lines_removed].to_s}"
puts line + " " * (border_line.length - line.length - 1) + "|"
puts empty_line

line = "| 🌐 Generated by Commit Counter 🌐"
puts line + " " * (border_line.length - line.length - 3) + "|"

line = "| 🔗 https://github.com/BSierakowski/github_commit_counter 🔗"
puts line + " " * (border_line.length - line.length - 3) + "|"

puts empty_line
puts border_line
puts ""
puts ""
